version: '3.8'
services:
  # app:
  #   container_name: nestjs_app
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - mongodb
  #     - redis
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  mongodb-express:
    image: mongo-express
    container_name: mongodb-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
