version: '3.8'
services:
  app:
    container_name: nestjs_app
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - mongodb-express
      - redis
    environment:
      DATABASE_URL: mongodb://mongodb:27017
      DATABASE_NAME: my_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_ID: 5fa87940-fc27-4c8d-8c6a-92f69e7f3139
      RATE_LIMIT_IP: 100
      RATE_LIMIT_TOKEN: 200

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  mongodb-express:
    image: mongo-express
    container_name: mongodb-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379